version: '3.9'
name: 'isdf'

services:
  scene:
    image: local_rap_scene:latest
    container_name: 'visinon_isdf_test'
    build:
      context: ./
    environment:
      - DISPLAY
      - XAUTORITY
      - QT_X11_NO_MITSHM=1
    ipc: host
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /etc/localtime:/etc/localtime:ro
      - /dev:/dev
